// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJOl6g-WI-5J2Go8xzLGnxq7hz1e15_gE',
    appId: '1:731957157447:web:25bd4550e61476a3681b62',
    messagingSenderId: '731957157447',
    projectId: 'mienmo-a9dc5',
    authDomain: 'mienmo-a9dc5.firebaseapp.com',
    storageBucket: 'mienmo-a9dc5.appspot.com',
    measurementId: 'G-88DF4RF3K4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI5t2luD7hBMfH7Dh5kFaPOMUigSlLLt4',
    appId: '1:731957157447:android:de89622c678ebd27681b62',
    messagingSenderId: '731957157447',
    projectId: 'mienmo-a9dc5',
    storageBucket: 'mienmo-a9dc5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-v5aOc5T0hD530nes62shpBUwwAi1JSk',
    appId: '1:731957157447:ios:aa19814ac66b6257681b62',
    messagingSenderId: '731957157447',
    projectId: 'mienmo-a9dc5',
    storageBucket: 'mienmo-a9dc5.appspot.com',
    iosBundleId: 'com.ridy.taxi.rider',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-v5aOc5T0hD530nes62shpBUwwAi1JSk',
    appId: '1:731957157447:ios:104ea0eb5f2db094681b62',
    messagingSenderId: '731957157447',
    projectId: 'mienmo-a9dc5',
    storageBucket: 'mienmo-a9dc5.appspot.com',
    iosBundleId: 'com.gotaxi.taxi.riderFlutter',
  );
}
